

service: aws-node-eventbridge-serverless

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev

  iamRoleStatements:
    - Effect: Allow
      Action:
        - events:PutEvents
      Resource: "*"

  environment:
    TRANSACTION_EVENT_BUS_NAME: transactions-${self:provider.stage}

custom:
  TRANSACTION_EVENT_BUS_NAME: transactions-${self:provider.stage}

functions:
  transactions:
   handler: handler.transactions
   events:
     - eventBridge:
        eventBus: ${self:custom.TRANSACTION_EVENT_BUS_NAME}
        pattern:
           source:
             - acme.transactions


  notify:
   handler: handler.hello
   events:
     - eventBridge:
        eventBus: marketing 
        pattern:
           source:
             - acme.newsletter.campaign



  xyzTransactions:
   handler: handler.xyz
   events:
     - eventBridge:
        eventBus: ${self:custom.TRANSACTION_EVENT_BUS_NAME}
        pattern:
           source:
             - acme.transactions.xyz

  sendTransaction:
    handler: handler.send

resources:
  Resources:
    TransactionsEventBus: 
      Type: AWS::Events::EventBus
      Properties:
        Name: ${self:custom.TRANSACTION_EVENT_BUS_NAME}
