

service: aws-node-eventbridge-serverless

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x

  iamRoleStatements:
    - Effect: Allow
      Action:
        - events:PutEvents
      Resource: "*"


functions:
  transactions:
   handler: handler.transactions
   events:
     - eventBridge:
        eventBus: transactions 
        pattern:
           source:
             - acme.transactions


  notify:
   handler: handler.hello
   events:
     - eventBridge:
        eventBus: marketing 
        pattern:
           source:
             - acme.newsletter.campaign
#   xyzTransactions:
#     handler: handler.xyz
#     memorySize: 128
#     events:
#       - eventBridge:
#           eventBus: transactions
#           pattern:
#             source:
#               - acme.transactions.xyz

  sendTransaction:
    handler: handler.send